/*
This header file includes all token types supported by the scanner.
*/

#ifndef SAVVY_TOKENS_H
#define SAVVY_TOKENS_H

namespace Savvy
{
	enum TokenType
	{
		SAVVY_EOF = 0,
		SAVVY_INTEGER_VALUE,
		SAVVY_FLOAT_VALUE,
		SAVVY_BOOL_VALUE,
		SAVVY_IDENTIFIER,
		SAVVY_OPEN_BRACKET,
		SAVVY_CLOSE_BRACKET,
		SAVVY_OPEN_SQUARE_BRACKET,
		SAVVY_CLOSE_SQUARE_BRACKET,
		SAVVY_OPEN_BRACE,
		SAVVY_CLOSE_BRACE,
		SAVVY_DATA_TYPE,
		SAVVY_OPERATOR,
		SAVVY_INSTRUCTION_END,
		SAVVY_RETURN_KEYWORD,
		SAVVY_IF_STATEMENT,
		SAVVY_ELSE_STATEMENT,
		SAVVY_SWITCH_STATEMENT,
		SAVVY_CASE_STATEMENT,
		SAVVY_BREAK_STATEMENT,
		SAVVY_FOR_STATEMENT,
		SAVVY_DO_STATEMENT,
		SAVVY_WHILE_STATEMENT,
		SAVVY_CONTINUE_STATEMENT,
		SAVVY_BUILT_IN_FUNCTION,
		SAVVY_LANGUAGE_SPECIFIC_KEYWORD,
		SAVVY_INCLUDE,
		SAVVY_STRING,
		SAVVY_PREPROCESSOR,
		SAVVY_NEW_LINE,
		SAVVY_UNKNOWN_TOKEN
	};
}

#endif // !SAVVY_TOKENS_H